language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: WtwWAEthcFcZPlAShJE3fwQv28QUuV2LxAbnJeykMg/uv4CiX4eeJIcaahu6ezr/5CwnazfuAZY+mlYBXHRMwkLfzaM1AbRNcHsRX+TToXWqM1L9GLKVQk6lfKLuI9RvWovfxIKY5Ylus7kcebdHNa1thx0Ao7E3d18Ap5TV6yh8URuaUFLVGBMpfwh3vECoVWRLOGSQAeoYYCUulfULeogAPDolkqRQHER3fwMVYxmvpABj2cgYK2u5oXZlxQvbC+JOVpaKkcSMqbl13cEYnZrm5R0fp2T68UIXdb8Wgk4bnIcjTIO1BgwjQz01ZopUdWMec87OGZ4zJnfKXmEZhHwar/oMZCah6ObvaUBoFa8GgLOkFnrnGFpsdbvGgb5FVwrngFMfP94o2GUJRBhg2hV6OBm5CN5TiwYxHAMXuTUdhFz6Us+BOjXWneh1Qd6u02C1XACKDqskTqh0GQk7kDe8z7mqSYXvEzbvv5dkSCVyDY933d1TPcp/feihi5Fjs0pk4ZBs0sxpo3If3VQbj//gEe2zp8rcCzObsFepp6kTMF0SoE1AT00Wfvj6PgOiJBY/mrzXA8Gkcrg7ek9boa9AjPeJU0QDax+qbqa1omdJmWL7rEU0UoBfdFZF82AD550wXuo08x9fCTwSEQ6hKRNr6r564f2ojFi8fsT/z1Q=
  app: sheltered-mountain-28335
  on:
    repo: rcaseyx/nbfapi
